#!/bin/bash

# The script in this file was generated by Gemini

# Set the output file
README_FILE="README.md"

# Write the static header to the README file
cat > "$README_FILE" << EOL
# Muso Dojo Images

This repository contains a collection of fun images generated by Google Gemini for the "Muso Dojo" project. Muso Dojo is a suite of tools designed to help musicians play and practice music.

_This README is auto-generated._

## Images

EOL

# Find all files in img/, sort by modification time (newest first),
# and append the markdown image tag to the README file.
for img in $(ls -tr img/); do
  echo "![Gemini Generated Image](img/$img)" >> "$README_FILE"
done

echo "README.md has been updated."
